// SPDX-License-Identifier: GPL-3.0-or-later
//
// AbobaVST3Processor.h — VST3 audio processor declaration.
#pragma once

#include "public.sdk/source/vst/vstaudioeffect.h"
#include "pluginterfaces/base/funknown.h"

#include "aboba/backend.hpp"
#include "aboba/pipeline.hpp"

#include <memory>
#include <vector>

namespace aboba_vst3 {

// Plugin UIDs. These are arbitrary but MUST be stable across versions.
// Generated by uuidgen and frozen here. Do not change.
static const Steinberg::FUID kAbobaProcessorUID(
    0xAB0BA001, 0x4F00CE5D, 0x12345678, 0x9ABCDEF0);
static const Steinberg::FUID kAbobaControllerUID(
    0xAB0BA002, 0xCT2L1234, 0x56789ABC, 0xDEF01234);

class Processor : public Steinberg::Vst::AudioEffect {
public:
    Processor();
    ~Processor() override;

    static Steinberg::FUnknown* createInstance(void*) {
        return static_cast<Steinberg::Vst::IAudioProcessor*>(new Processor());
    }

    Steinberg::tresult PLUGIN_API initialize(Steinberg::FUnknown* context) override;
    Steinberg::tresult PLUGIN_API terminate() override;
    Steinberg::tresult PLUGIN_API setActive(Steinberg::TBool state) override;
    Steinberg::tresult PLUGIN_API setupProcessing(Steinberg::Vst::ProcessSetup& setup) override;
    Steinberg::tresult PLUGIN_API process(Steinberg::Vst::ProcessData& data) override;
    Steinberg::tresult PLUGIN_API setState(Steinberg::IBStream* state) override;
    Steinberg::tresult PLUGIN_API getState(Steinberg::IBStream* state) override;

private:
    void handle_param_change(Steinberg::Vst::ParamID id, double value);
    void apply_all_params();

    // Aboba state
    std::unique_ptr<aboba::Backend>       backend_;
    std::unique_ptr<aboba::VoicePipeline> pipeline_;

    // Pre-allocated scratch buffers (sized in setupProcessing)
    std::vector<float> mono_in_;
    std::vector<float> mono_out_;

    // Cached parameter values (so we can apply them after construction)
    double sample_rate_      = 48000.0;
    Steinberg::int32 max_block_ = 1024;
    float pitch_semitones_    = 0.0f;
    float formant_semitones_  = 0.0f;
    int   character_idx_      = 0;
    bool  reverb_enabled_     = false;
    float reverb_wet_         = 0.2f;
    bool  autotune_enabled_   = false;
    int   autotune_scale_idx_ = 0;
    float autotune_strength_  = 1.0f;
    bool  bypass_             = false;
};

}  // namespace aboba_vst3
